### ISSUE TITLE
next app does not build 

### ISSUE THREAD

**Issue by dnfd** [actpohabtNS/hackademy-week-5#3]
> Build error occurred
Error: Export encountered errors on following paths:
	/
	/404
	/500
	/components/WeatherTable
	/forecast
	/login
    at /usr/lib/node_modules/next/dist/export/index.js:487:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/usr/lib/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async /usr/lib/node_modules/next/dist/build/index.js:833:17
    at async Span.traceAsyncFn (/usr/lib/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async /usr/lib/node_modules/next/dist/build/index.js:707:13
    at async Span.traceAsyncFn (/usr/lib/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async Object.build [as default] (/usr/lib/node_modules/next/dist/build/index.js:77:25)

**Comment by nksazonov** [comment]
_npm run build_ output:

```
> react-next-app@0.1.0 build
> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
error - ESLint: Failed to load config "next/babel" to extend from. Referenced from: D:\Files\Front-End\Study\hackademy\hackademy-week-5\react-next-app\.eslintrc.json
info  - Using external babel configuration from D:\Files\Front-End\Study\hackademy\hackademy-week-5\react-next-app\.babelrc
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (6/6)
info  - Finalizing page optimization
```

Is the problem workspace specific?

**Comment by nksazonov** [comment]
Have just cloned and built the project at my linux machine. Everything builds fine.
